[package]
name = "upon"
version = "0.1.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2021"
description = "A simple, powerful template engine"
readme = "README.md"
repository = "https://github.com/rossmacarthur/upon"
license = "MIT OR Apache-2.0"
keywords = ["string", "format", "template", "engine"]
categories = ["template-engine"]

[dependencies]
serde = "1.0.137"
unicode-width = "0.1.9"

[dev-dependencies]
serde = { version = "1.0.137", features = ["derive"] }

[workspace]
members = ["benches"]

[profile.bench]
debug = true
