[package]
name = "upon"
version = "0.2.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2021"
description = "A simple, powerful template engine"
readme = "README.md"
repository = "https://github.com/rossmacarthur/upon"
license = "MIT OR Apache-2.0"
keywords = ["string", "format", "template", "engine"]
categories = ["template-engine"]

[features]
default = ["unicode"]

# Only used for displaying errors
# If disabled then chars().count() will be used instead
unicode = ["dep:unicode-width"]

[dependencies]
serde = "1.0.137"
unicode-width = { version = "0.1.9", optional = true }

[dev-dependencies]
serde = { version = "1.0.137", features = ["derive"] }

[workspace]
members = ["benches", "tools/*"]
