[package]
name = "fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
upon = { path = ".." }

[[bin]]
name = "compile"
path = "src/compile.rs"
test = false
doc = false
