[package]
name = "gen-readme"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.58"
pulldown-cmark = "0.9.1"
pulldown-cmark-to-cmark = "10.0.2"
upon = { path = "../.." }
