name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:

  # ---------------------------------------------------------------------------
  # Lint
  # ---------------------------------------------------------------------------

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, beta, nightly]

    env:
      RUSTFLAGS: --deny warnings

    steps:
    - uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
        components: clippy, rustfmt

    - name: Rustfmt
      run: cargo fmt -- --check

    - name: Clippy
      run: cargo clippy --workspace --all-targets

    - name: Check (internal debug)
      run: cargo check
      env:
        RUSTFLAGS: --deny warnings --cfg internal_debug

    - name: Check README
      run: cargo run --package gen-readme -- --check

  # ---------------------------------------------------------------------------
  # Test
  # ---------------------------------------------------------------------------

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Test
        run: cargo test --workspace

      - name: Test (no default features)
        run: cargo test --lib --tests --no-default-features

      - name: Test (filters)
        run: cargo test --lib --tests --no-default-features --features filters

      - name: Test (serde)
        run: cargo test --lib --tests --no-default-features --features serde

      - name: Test (unicode)
        run: cargo test --lib --tests --no-default-features --features unicode

      - name: Test (filters,serde)
        run: cargo test --lib --tests --no-default-features --features filters,serde

      - name: Test (serde,unicode)
        run: cargo test --lib --tests --no-default-features --features serde,unicode

      - name: Test (filters,unicode)
        run: cargo test --lib --tests --no-default-features --features filters,unicode

  # ---------------------------------------------------------------------------
  # Check README
  # ---------------------------------------------------------------------------

  readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Check README
      run: cargo run --package gen-readme -- --check

  # ---------------------------------------------------------------------------
  # Check version against tag
  # ---------------------------------------------------------------------------

  check-version:
    needs: [lint, test, readme]
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Calculate version from tag
        id: version
        run: echo "::set-output name=value::${GITHUB_REF#refs/tags/}"

      - name: Check tag against package version
        run: grep '^version = "${{ steps.version.outputs.value }}"$' Cargo.toml

  # ---------------------------------------------------------------------------
  # Publish to Crates.io
  # ---------------------------------------------------------------------------

  publish:
    needs: check-version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      run: cargo publish
